language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule==2.22 apache-libcloud
env:
  global:
  - secure: Kl0qH/PnSL7nAWuZtkD61KrofFPhWDk9f6GMqrrJmxnTq0a12wIUiCi8Sx72LB6iAZ51s4wmAcYBVoyTJ2kMcd9FJWTmVA7wgPy6ALblbVna8wXAsfL1muvyeiH2MB5J5fkSeWV5jin+bYxq66LaARp35+ekD5X3X4ngAPIyxV9ja94mj8Xx9rKL/hC43n8B0uaT7mSwd+vw5OIyltNxTjdzgj5uuBkEK1NTmZhJIBEzlbB3DN1rq78Mz0LrA7mqGzSrf5vYvz9VeeTzeSVb0MthtUWJ9Y2xP9eVnLcWq4Vkn3E8FrFpyxjKuUIfBSul1Qh4GiMpqdO3lq3hJvGoR2gDn+05IKbnT3I8QmPac5CfEPctR/6wTcEqAf6Gd/x+I/ft2XZMyd31B6nQL6JZuc1JKH+dKQGg4yysXqIQue/De1jjgV5L8tZcBvROUbWUCcvFTSiJJPtCeqTiFTWxzl2lKSjMjIYvMeFGaDMXY6ShdcOnGMhuASyAOZ+NVs6fqjX7ZEaVPfJ8MRW3sDsEm5NZHykgjxG9XQIXKbIRUsz4t8kR8TXzLB+Qq8IMJOrLbkPF2knMHwvesXOiK/Iv0bXasDvDsPY+A2zc2bpzoKJ5pq1X9N6xIISI3NX1jZVdL8k3qsC3/kbA29Uiyc56jfwdnMCuCV+vdC8Qmr0M3HI=
  - secure: fyTa5O9VJu3R4d4geCAJxvcYm1Z/uTPpOdque8/3r8tK4jeZEn3BlP6G5IGErg6rUp5Y3osy0PNaEVwyPE+icbY8e6kvnxdzgGtYbF3egSHDhXl/V2XoF1yYtGtmLqHqkVEl1Ci5SWaaq4XGtilGayXTRwaoG0S+NOyePYLRC0A+N0hWXmNdF9YGxN6cwsCZTJnvQEHbJ5mdADhSXT0emo/+Z0CGQ0Z6tHULvFSmlEQPItJKEwQ09txWDYk+Vvfclx1rHKYJGIer6M93qa+bZ281jPSMMRQ5P3gB/CE1v26pxQaZT5+2peWapofMu1hqgfrMLQie34qqQV5yPhZv6StE+vvW2rHOpGRHUxeu/ib69SIYcWL/9mm6oaf8OGyoJqLa5LCQj4OHRDu0bI2rEbrgk2AXHITN34B5x8Q44ymulM60Yoo2cTALYGJWfyCI5Dl7CI6WWFTsVehoWegkWcCO1e/8Gsr9tsdL5vhGrsvJGxTY2ccCBWK92mqVxpqDCYpYRNlqJ5WTr81zWN4R7++xZ+j4yQVjWp31qxbzshwPJjpuvEan/XduihrgjTFrkirw9I2DROdToXY5rAu36kwpEVvCZLzAxL8QCfGYDtS0SgqSUD2lJP+pWwqn3ypms8hyvpy/YnmPdEIRAyJEO2m6GjGrwy1sdrLIThpMaj0=
  - secure: KJy9N0PMXc4lZ2FbVCnPKtBJgwa/we6jj7iaSXn+qOsbMR3qnJ1z8VTfOocW0h52x7oLpYnABNOnS6XLmmyCrzwgert55RHhKuWUKsre3hFqMAJSm5R5FuVxBCJUvFYJjTDrNlfPfPmpPYC+fO8w++1khlu0BkQaCRJ3BVSDvyWt7tUNPHmaekoAgreSB4ADaWQSIQFwAjE2r9vylKZuFJ6wOnQPmO5bd7ZzbFpYBIVtgjebK4jq6KalPNBHpcYC50IiyATvwVrYRNRC7GJBRYe2L9hWVctVxDRfqtOhdNn7dmJfQ2dvPfdZfaRKVG1ZCnfMHLwp4xLoBwjl3Lb2POs34YTRteB0x/RmxA51NEGWenxXsuppJHMzUuN7Qek8VnbYsKBsgS1T5qFxFp/QPJp2RhMHfcFPfVyRkrmY3aUAHadyAzwTBaPFhAyVgpivcjPGiSYPzpW2Y5POk+pjwmqsaIsbeEFQCSTvg28Zee9oorgsHIBi9wuZxMZkczoZMYru/ZsOLU6dB+yaQlNMyMKIEoSLO5lZXVZmoZN52aL0zywLQOYyGhv7yh/smaoP2GBQ1wJlmuXMBt/xVKKcGTFcjJWfq79mO/VvotbWPy7aOO8DBoLFYEMlbfF8dIBw8hFWnNc3LLM/+OI0gY/+YRr0S4vCJt+WFw1ZwcSIelk=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
