---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance-travis
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1804-bionic-v20201116
provisioner:
  name: ansible
  log: true
  connection_options:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no 
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
